### ISSUE TITLE
"Unassigned address called" error running latest riscv-linux

### ISSUE THREAD

**Issue by sirnewton01** [riscv/riscv-qemu#10]
I compiled the latest riscv gcc cross compiler using a Linux x86 VM and used it to compile the latest riscv-linux kernel, assemble a root image using busy box, etc.

I can run the kernel, root image and Berkeley Boot Loader with the spike simulator like this:
spike +disk=root.bin bbl vmlinux

However, when I run the same kernel and root image using riscv-qemu with the following arguments I get an error (shown below):
qemu-system-riscv -hda root.bin -kernel vmlinux -nographic

Output shows the following and emu quickly terminates:
unassigned address was called?
with addr: FFFFFFFFFFFFFFD8
not implemented for riscv

The same version of riscv-qemu can run the pre-built vmlinux and root.bin provided as downloads from the README.md.

**Comment by sbeamer** [comment]
riscv-qemu is not up to date with the most recent privileged spec, but the update is currently ongoing.

**Comment by a0u** [comment]
Unfortunately, riscv-qemu has not yet been updated for v1.7 of the privileged ISA.  At the moment, you must stick with the master branch of riscv-linux along with a pre-1.7 toolchain
(e.g., riscv/riscv-gnu-toolchain@f0addb7a8ce29ff2f7fd7c15942380208a513cd4).

**Comment by sirnewton01** [comment]
Thanks, I hadn't dug deep enough to know that this is related to the out of date privileged ISA or not. Is there a branch for work there? Anything I can do to help?

**Comment by sagark** [comment]
Fixed in 7ecbff9109f338ed40e58164e38d40f415b4bb99
