### ISSUE TITLE
riscv-qemu does not compile

### ISSUE THREAD

**Issue by ForceFaction** [riscv/riscv-qemu#100]
Hey, the build fails with this (https://pastebin.com/iZvGG9YP) error message. What am i doing wrong ?

**Comment by bkoppelmann** [comment]
I don't know what these errors mean. However, you're trying to build the aarch64 frontend. Try running configure --target-list=riscv64-softmmu

Cheers,
Bastian

**Comment by ForceFaction** [comment]
Thx, it now builds the riscv64/32-softmmu targets. It only fails when trying to build the riscv-linux-user targets.
