### ISSUE TITLE
unable to build on Fedora 23 

### ISSUE THREAD

**Issue by YaoFei509** [riscv/riscv-qemu#12]
CC    vl.o
vl.c: 在函数‘main’中:
vl.c:2972:5: 错误：‘g_mem_set_vtable’ is deprecated [-Werror=deprecated-declarations]
     g_mem_set_vtable(&mem_trace);
     ^
In file included from /usr/include/glib-2.0/glib/glist.h:32:0,
                 from /usr/include/glib-2.0/glib/ghash.h:33,
                 from /usr/include/glib-2.0/glib.h:50,
                 from vl.c:59:
/usr/include/glib-2.0/glib/gmem.h:357:7: 附注：在此声明
 void  g_mem_set_vtable (GMemVTable *vtable);
       ^
cc1：所有的警告都被当作是错误
/home/yaofei/src/riscv/riscv-qemu/rules.mak:33: recipe for target 'vl.o' failed
make: *** [vl.o] Error 1

**Comment by coypoop** [comment]
I had this problem as well using Fedora-24, I took some qemu upstream patches to fix it, and made pull request #13.

**Comment by sagark** [comment]
Now that riscv-qemu is rebased, this should be fixed. Let me know if something is still wrong.
