### ISSUE TITLE
The continuity of this repo

### ISSUE THREAD

**Issue by NonerKao** [riscv/riscv-qemu#121]
It's good to see this port gets upstream.  Congratulations!

But I wonder, is this repo going to continue? or all the work afterward will be upstream, just like riscv-binutils-gdb?

Thanks!

**Comment by michaeljclark** [comment]
It's likely that this repo will continue as we'll use it to host features that have not yet been merged upstream.

We are following the model of the `riscv-linux` repo mode where we have a `riscv-all` branch that contains upstream plus work in progress branches that have not yet been merged upstream.

Currently the `riscv-all` branch contains a number of bug fixes that have not yet made it upstream.

**Comment by michaeljclark** [comment]
I'm closing this issue. We are using this repo to hold issues and patches before upstream review and acceptance.
