### ISSUE TITLE
I can't do git clone

### ISSUE THREAD

**Issue by yosukezith** [riscv/riscv-qemu#134]
I can't do git clone these directory.
(capstone, dtc, io/keycodemapdb)

What should I do?

**Comment by jim-wilson** [comment]
It helps if you report the exact error that you received.  However, it is a reasonable assumption that this is the same problem reported in these two places.  Try the workarounds mentioned there.
https://github.com/riscv/riscv-gnu-toolchain/issues/324
https://github.com/riscv/riscv-gnu-toolchain/issues/280
