### ISSUE TITLE
compilation error (undefined functions) unless --disable-werror

### ISSUE THREAD

**Issue by manuelafm** [riscv/riscv-qemu#16]
```
  CC    riscv-softmmu/cpu-exec-common.o
In file included from /archive/toolchain/riscv-qemu/include/qemu-common.h:53:0,
                 from /archive/toolchain/riscv-qemu/tcg/tcg.c:39:
/archive/toolchain/riscv-qemu/target-riscv/cpu.h:434:13: error: inline function 'cpu_riscv_tlb_flush' declared but never defined [-Werror]
 inline void cpu_riscv_tlb_flush (CPURISCVState *env, int flush_global);
             ^
In file included from /archive/toolchain/riscv-qemu/cpu-exec.c:20:0:
/archive/toolchain/riscv-qemu/target-riscv/cpu.h:434:13: error: inline function 'cpu_riscv_tlb_flush' declared but never defined [-Werror]
 inline void cpu_riscv_tlb_flush (CPURISCVState *env, int flush_global);
             ^
In file included from /archive/toolchain/riscv-qemu/include/qemu-common.h:53:0,
                 from /archive/toolchain/riscv-qemu/translate-all.c:33:
/archive/toolchain/riscv-qemu/target-riscv/cpu.h:434:13: error: inline function 'cpu_riscv_tlb_flush' declared but never defined [-Werror]
 inline void cpu_riscv_tlb_flush (CPURISCVState *env, int flush_global);
             ^
In file included from /archive/toolchain/riscv-qemu/include/qemu-common.h:53:0,
                 from /archive/toolchain/riscv-qemu/translate-common.c:20:
/archive/toolchain/riscv-qemu/target-riscv/cpu.h:434:13: error: inline function 'cpu_riscv_tlb_flush' declared but never defined [-Werror]
 inline void cpu_riscv_tlb_flush (CPURISCVState *env, int flush_global);
             ^
In file included from /archive/toolchain/riscv-qemu/cpu-exec-common.c:21:0:
/archive/toolchain/riscv-qemu/target-riscv/cpu.h:434:13: error: inline function 'cpu_riscv_tlb_flush' declared but never defined [-Werror]
 inline void cpu_riscv_tlb_flush (CPURISCVState *env, int flush_global);
             ^
cc1: all warnings being treated as errors
/archive/toolchain/riscv-qemu/rules.mak:57: recipe for target 'translate-common.o' failed
```

**Comment by manuelafm** [comment]
./configure --disable-werror, I mean.

But of course, better to fix the problem properly by either defining the functions or removing the declaration.

**Comment by manuelafm** [comment]
Another problem after fixing the above:
```
hw/riscv/cputimer.c:55:32: error: ‘instret_delta’ is static but used in inline function ‘instret_read_with_delta’ which is not static [-Werror]
     return instret_read(env) + instret_delta;
```

**Comment by sagark** [comment]
Thanks for the report, I will take care of this. What compiler/version are you using so I can replicate? I don't get this with gcc 4.8.4.

**Comment by manuelafm** [comment]
I was using GCC 5.3.

**Comment by jhdulaney** [comment]
I see this as well with gcc 6.0

**Comment by jhdulaney** [comment]
Also, I see:

/builddir/build/BUILD/riscv-qemu/hw/riscv/htif/frontend.c: In function 'sys_close':
/builddir/build/BUILD/riscv-qemu/hw/riscv/htif/frontend.c:78:46: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'uint64_t {aka long long unsigned int}' [-Wformat=]
         fprintf(stderr, "INVALID close fd: %ld. only 3 allowed\n", fd);
                                              ^
/builddir/build/BUILD/riscv-qemu/hw/riscv/htif/frontend.c: In function 'sys_pread':
/builddir/build/BUILD/riscv-qemu/hw/riscv/htif/frontend.c:121:46: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'uint64_t {aka long long unsigned int}' [-Wformat=]
         fprintf(stderr, "INVALID pread fd: %ld. only 3 allowed\n", fd);
                                              ^
/builddir/build/BUILD/riscv-qemu/hw/riscv/htif/frontend.c: In function 'sys_exit':
/builddir/build/BUILD/riscv-qemu/hw/riscv/htif/frontend.c:138:31: warning: format '%ld' expects argument of type 'long int', but argument 2 has type 'uint64_t {aka long long unsigned int}' [-Wformat=]
     printf("sys_exit. code: %ld\n", code << 1 | 1);
                               ^
/builddir/build/BUILD/riscv-qemu/hw/riscv/htif/frontend.c: In function 'handle_frontend_syscall':
/builddir/build/BUILD/riscv-qemu/hw/riscv/htif/frontend.c:208:49: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'uint64_t {aka long long unsigned int}' [-Wformat=]
             fprintf(stderr, "FRONTEND SYSCALL %ld NOT IMPLEMENTED\n", mm[0]);

and

In file included from /builddir/build/BUILD/riscv-qemu/include/qemu-common.h:53:0,
                 from /builddir/build/BUILD/riscv-qemu/include/hw/hw.h:5,
                 from /builddir/build/BUILD/riscv-qemu/include/hw/riscv/htif/htif.h:26,
                 from /builddir/build/BUILD/riscv-qemu/hw/riscv/htif/frontend.c:30:
/builddir/build/BUILD/riscv-qemu/hw/riscv/htif/frontend.c: At top level:
/builddir/build/BUILD/riscv-qemu/target-riscv/cpu.h:434:13: warning: inline function 'cpu_riscv_tlb_flush' declared but never defined
 inline void cpu_riscv_tlb_flush (CPURISCVState *env, int flush_global);

**Comment by jhdulaney** [comment]
/builddir/build/BUILD/riscv-qemu/target-riscv/translate_init.c:21:28: warning: left shift count >= width of type [-Wshift-count-overflow]
 #define MCPUID_RV64I   (2L << 62)
                            ^
/builddir/build/BUILD/riscv-qemu/target-riscv/translate_init.c:41:28: note: in expansion of macro 'MCPUID_RV64I'
         .init_mcpuid_reg = MCPUID_RV64I | MCPUID_SUPER | /*MCPUID_USER |*/ MCPUID_I
                            ^~~~~~~~~~~~

**Comment by jhdulaney** [comment]
However, what ultimately causes build failure on gcc 6 is this:

In file included from /builddir/build/BUILD/riscv-qemu/target-riscv/translate.c:21:0:
/builddir/build/BUILD/riscv-qemu/target-riscv/cpu.h:434:13: warning: inline function 'cpu_riscv_tlb_flush' declared but never defined
 inline void cpu_riscv_tlb_flush (CPURISCVState *env, int flush_global);
             ^~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c: In function 'helper_mulhsu':
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c:486:23: error: '__int128_t' undeclared (first use in this function)
     return (int64_t)((__int128_t)a*b >> 64);
                       ^~~~~~~~~~
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c:486:23: note: each undeclared identifier is reported only once for each function it appears in
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c:486:34: error: expected ')' before 'a'
     return (int64_t)((__int128_t)a*b >> 64);
                                  ^
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c:485:14: warning: unused variable 'b' [-Wunused-variable]
     uint64_t b = arg2;
              ^
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c:484:13: warning: unused variable 'a' [-Wunused-variable]
     int64_t a = arg1;
             ^
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c: In function 'helper_debug_print':
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c:901:25: warning: format '%lx' expects argument of type 'long unsigned int', but argument 4 has type 'target_ulong {aka long long unsigned int}' [-Wformat=]
         fprintf(stderr, ": core   0: 0x" TARGET_FMT_lx " (0x%08lx) %s",
                         ^~~~~~~~~~~~~~~~
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c: In function 'riscv_cpu_do_unaligned_access':
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c:1014:24: warning: format '%lx' expects argument of type 'long unsigned int', but argument 2 has type 'target_ulong {aka long long unsigned int}' [-Wformat=]
     printf("addr: %016lx\n", addr);
                        ^
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c: In function 'riscv_cpu_unassigned_access':
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c:1047:38: warning: format '%lX' expects argument of type 'long unsigned int', but argument 2 has type 'hwaddr {aka long long unsigned int}' [-Wformat=]
     printf("unassigned Address: %016lX\n", addr);
                                      ^
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c: At top level:
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c:974:21: warning: 'riscv_env_get_cpu' is static but used in inline function 'cpu_riscv_tlb_flush' which is not static
     RISCVCPU *cpu = riscv_env_get_cpu(env);
                     ^~~~~~~~~~~~~~~~~
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c: In function 'helper_mulhsu':
/builddir/build/BUILD/riscv-qemu/target-riscv/op_helper.c:487:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/builddir/build/BUILD/riscv-qemu/rules.mak:57: recipe for target 'target-riscv/op_helper.o' failed

**Comment by sagark** [comment]
gcc-5 issues should be fixed as of 8dac7fc640f954fae7b5a7aaded5d9980a3738f5

**Comment by manuelafm** [comment]
That's great, thanks!

**Comment by michaeljclark** [comment]
Closing this issue as it appears to be resolved. Performed test build on distros with -Werror

**Comment by manuelafm** [comment]
Thanks @michaeljclark !
