### ISSUE TITLE
the issue: qemu-system-riscv64: -nographic: unsupported machine type

### ISSUE THREAD

**Issue by eleven121** [riscv/riscv-qemu#177]
Hi
I have installed the riscv-tools and download the image of the linux kernl. Then I built the qemu using apt-get install qemu. When I used the qemu simulate this image using the command:
qemu-system-rscv64 -nographic -machine virt -smp 4 -m 512M -kernel bbl...
The problem displays:
qemu-system-riscv64: -nographic: unsupported machine type

and the qemu-system-riscv64 's version is 2.7.50. Is the qemu too old?
Thanks.

**Comment by jim-wilson** [comment]
Yes, the qemu is too old.  You need to check out riscv/riscv-qemu and build it.

**Comment by michaeljclark** [comment]
This one seems to be resolved. Thanks @jim-wilson
