### ISSUE TITLE
How can I found VIDEO BIOS Extensions information in riscv-qemu

### ISSUE THREAD

**Issue by LoveZJT** [riscv/riscv-qemu#193]
I want to get VIDEO BIOS Extensions information, such as framebuffer, width and height of screen. I can't find the address of it. So how can I found VIDEO BIOS Extensions information in riscv-qemu? Or which files should I read?

**Comment by jim-wilson** [comment]
This tree is not actively maintained, and is not a good place to ask questions.

RISC-V is an ISA, not a graphics device, so this is the wrong place to look.  Presumably you can choose any graphics device, and then for programming details you have to look at the documentation for that graphics device.
