### ISSUE TITLE
Reg. pixman folder update

### ISSUE THREAD

**Issue by susi655** [riscv/riscv-qemu#20]
$git submodule update --init pixman

Cloning into 'pixman'...
fatal: unable to connect to anongit.freedesktop.org:
anongit.freedesktop.org[0: 131.252.210.161]: errno=Connection refused
anongit.freedesktop.org[1: 2610:10:20:722:a800:ff:fe24:61cf]: errno=Network is unreachable

Clone of 'git://anongit.freedesktop.org/pixman' into submodule path 'pixman' failed

Can you tell the alternative way to update pixman submodule

**Comment by susi655** [comment]
I had updated pixman using 
    git clone http://anonscm.debian.org/cgit/pkg-xorg/lib/pixman.git

And then i installed qemu..
Will it satisfies the requirements of qemu?

**Comment by sagark** [comment]
Sounds like you have a network connectivity issue that prevents you from accessing git://anongit.freedesktop.org/pixman (this is still used in upstream QEMU and I was able to clone it just now). Are you able to access https://cgit.freedesktop.org/pixman/ ?

If you're able to build with that version of pixman, it should be fine.
