### ISSUE TITLE
update performance counter CSRs

### ISSUE THREAD

**Issue by sashimi-yzh** [riscv/riscv-qemu#21]
Using the newest riscv-gcc to build bbl and linux can not run in riscv-qemu, since the performance counter definitions in riscv-qemu are not matched to the code generated by riscv-gcc.

**Comment by sagark** [comment]
riscv-qemu usually bumps when new priv spec versions are "released" (i.e. there's a document that goes with them) rather than tracking WIP commits to riscv-tools. You can use the latest v1.9 release in the meantime: https://github.com/riscv/riscv-tools/releases/tag/priv-1.9-rc0
