### ISSUE TITLE
Nonzero retval from testing script

### ISSUE THREAD

**Issue by alexmechanic** [riscv/riscv-qemu#23]
Running hacking_files/run_riscv_tests.py, getting error for every test:

```
../riscv32-softmmu/qemu-system-riscv32 -m 3840M -kernel /media/psf/work/riscv/risc_v/test-suite/isa/rv32ui-v-ori -nographic
NONZERO RETVAL for rv32ui-v-ori
139
```

Running QEMU manually for any test results in segfault

**Comment by sagark** [comment]
I'm not able to reproduce this on my end. Could you provide more details about your environment?

**Comment by alexmechanic** [comment]
Ubuntu 16.04LTS, all packages needed are installed, pulled latest riscv-qemu repo and built both 32/64 bit riscvXX-softmmu. tests are from riscv-tools repo.
Anything else?

**Comment by sagark** [comment]
What are the commit hashes from riscv-tools/tests?

**Comment by alexmechanic** [comment]
I don't know, latest? Didn't get into commits, just trying to build all I've got
https://github.com/riscv/riscv-tests/commit/c9022d2f63f50388b2ab1192966f30dbe7819a59

**Comment by sagark** [comment]
You need to use the priv1.9 release version of riscv-tools with qemu:
https://github.com/riscv/riscv-tools/releases/tag/priv-1.9-rc0

**Comment by alexmechanic** [comment]
So QEMU is already on v1.9? Okay I'll try that
Is it always up to latest version of RISC-V?

**Comment by alexmechanic** [comment]
For priv-1.9, I don't see an option for 32bit compliling. Is it not implemented by now?

**Comment by alexmechanic** [comment]
Build of priv-1.9 branch fails.
**using main build.sh:**
gengtype-lex.c: In function ‘int yy_get_next_buffer()’:
gengtype-lex.c:2222:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/bin/bash: line 3: 28396 Killed                  makeinfo --split-size=5000000 --split-size=5000000 --no-split -I . -I /home/alex/riscv-tools/riscv-gnu-toolchain/build/src/newlib-gcc/gcc/doc -I /home/alex/riscv-tools/riscv-gnu-toolchain/build/src/newlib-gcc/gcc/doc/include -o doc/gccint.info /home/alex/riscv-tools/riscv-gnu-toolchain/build/src/newlib-gcc/gcc/doc/gccint.texi
make[3]: *** [doc/gccint.info] Error 137
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all-gcc] Error 2
make[1]: *** [all] Error 2
make: *** [stamps/build-gcc-newlib] Error 2
**using makefile from riscv-tests ($ make):**
median_main.o: In function `main':
median_main.c:(.text.startup+0x8): relocation truncated to fit: R_RISCV_HI20 against `.LANCHOR0'
collect2: error: ld returned 1 exit status
/home/alex/riscv-tools/riscv-tests/benchmarks/median/bmark.mk:28: recipe for target 'median.riscv' failed
make[1]: *** [median.riscv] Error 1
make[1]: Leaving directory '/home/alex/riscv-tools/riscv-tests/benchmarks'
Makefile:18: recipe for target 'benchmarks' failed
make: *** [benchmarks] Error 2

**using makefile from riscv-tests ($ make isa):**
rv32uf/../rv64uf/fcvt.S: Assembler messages:
rv32uf/../rv64uf/fcvt.S:27: Error: unrecognized opcode `fcvt.s.l f0,a0'
rv32uf/../rv64uf/fcvt.S:28: Error: unrecognized opcode `fcvt.s.l f0,a0'
rv32uf/../rv64uf/fcvt.S:30: Error: unrecognized opcode `fcvt.s.lu f0,a0'
rv32uf/../rv64uf/fcvt.S:31: Error: unrecognized opcode `fcvt.s.lu f0,a0'
/home/alex/riscv-tools/riscv-tests/isa/Makefile:75: recipe for target 'rv32uf-p-fcvt' failed
make[1]: *** [rv32uf-p-fcvt] Error 1
make[1]: Leaving directory '/home/alex/riscv-tools/riscv-tests/isa'
Makefile:22: recipe for target 'isa' failed
make: *** [isa] Error 2

**Comment by bkoppelmann** [comment]
Hi Alex,

unfortunately I cannot reproduce your first error completly. I only get an error for 4 tests:
```
['rv64uc-p-rvc', 'rv64uc-v-rvc', 'rv32uc-p-rvc', 'rv32uc-v-rvc']
```
However I was using the priv-1.9-rc0 tag of riscv-tools, and I cannot reproduce your build failures. Which version of gcc are you using?

**Comment by sagark** [comment]
By the way, those 4 tests should fail since RVC isn't implemented. I'll remove them from the test list to avoid confusion.

**Comment by alexmechanic** [comment]
bkoppelmann, if you ask about ```ggc -v```, then 
> gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)
I'm using priv-1.9-rc0 tag as well.
I will exclude those 4 tests from build and try again but i have errors **building** other tests as shown above

**Comment by alexmechanic** [comment]
**Update** to my issue:
Just reproduced building script (./build.sh) manually as script says, and it worked.
It might be something I missed from script, or script itself contains some errors, you probably would like to check.

Now, rebuilt QEMU and any test fails with error:
`riscv64-softmmu/qemu-system-riscv64 -m 3840M -kernel /opt/riscv/riscv64-unknown-elf/share/riscv-tests/isa/rv32ui-p-rem -nographic
qemu-system-riscv64: cannot set up guest memory 'riscv_board.ram': Cannot allocate memory`

**Comment by sagark** [comment]
Do you have enough memory to give QEMU 3840M?

**Comment by bkoppelmann** [comment]
Your machine does not have enought memory, try -m 1024M

**Comment by sagark** [comment]
By the way, one catch - due to the way riscv_board.c is currently written, you'll need 2GB + whatever you specify at the command line with -m.

**Comment by alexmechanic** [comment]
Was really my fault, VM memory was set too low.
With any avaliable value for -m QEMU freezes, not able to stop it except killing a process for most of the tests.
