### ISSUE TITLE
Can't remote debug program with qemu user mode

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-qemu#28]
Qemu hash = https://github.com/riscv/riscv-qemu/commit/8e35f13f02b68089476e9a018d03d0a955155dff

GNU Toolchain hash = https://github.com/riscv/riscv-gnu-toolchain/commit/80007506c6d284d632a08bee8526e88132ea277c

```
$ riscv64-unknown-linux-gnu-gcc ~/hello.c -o hello.rv64 -static -g3
$ qemu-riscv64 -g1234 hello.rv64
# In another terminal
$ riscv64-unknown-linux-gnu-gdb hello.rv64 
GNU gdb (GDB) 7.11.50.20160803-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-pc-linux-gnu --target=riscv64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from hello.rv64...done.
(gdb) target remote :1234
Remote debugging using :1234
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Ignoring packet error, continuing...
```

**Comment by sorear** [comment]
I have encountered this as well.

**Comment by alexmechanic** [comment]
Same errors. Suppose that riscv-gdb is still under dev, but would be good to hear something from the dev team.
+ question: is it required adding `-L $RISCV/sysroot` option for qemu when running GDB session?

**Comment by sagark** [comment]
I've restored gdb support as of 2ef31d248d16fa489ba86bd92727de5b5b9766ab

I've tested reading/writing registers (int regs, pc, fp regs), single stepping, and setting/continuing to breakpoints.

**Comment by alexmechanic** [comment]
I see it fixed for softmmu, is it ok with linux-user mode as well?

**Comment by kito-cheng** [comment]
@alexmechanic linux-user mode seem working too, I've tested with a hello word program :)

**Comment by sagark** [comment]
It should be fixed for both, linux-user mode gdb is just not documented in the readme.
