### ISSUE TITLE
risc-v tests success check

### ISSUE THREAD

**Issue by alexmechanic** [riscv/riscv-qemu#29]
Wanted to know, what is condition of passing riscv-tests? Couldn't find where is the checker for some value etc. in qemu.

**Comment by sagark** [comment]
System mode:
https://github.com/riscv/riscv-qemu/blob/master/hw/riscv/htif/htif.c#L163

Linux user mode:
IIRC this is an exit where zero exit status = success.

**Comment by alexmechanic** [comment]
What about t3 reg value? I see it equals 1 in many tests in <success> section, and in <fail> section its differs from 1
