### ISSUE TITLE
riscv-tests for QEMU

### ISSUE THREAD

**Issue by alexmechanic** [riscv/riscv-qemu#32]
Any test from riscv-tests faults in QEMU with ILLEGAL INST.
Readme says I should use ones from [https://github.com/arsv/riscv-qemu-tests](riscv-qemu-tests) repo for user-mode build. Is it correct that qemu-user-mode cannot run riscv-tests binaries?

**Comment by sagark** [comment]
Yes, you will need to use riscv-qemu-tests for user mode. User mode won't run plain riscv-tests binaries.
