### ISSUE TITLE
Cannot allocate Memory

### ISSUE THREAD

**Issue by shrshore** [riscv/riscv-qemu#39]
When I boot the linux kernel with qemu, it just reminds me that
```
shore@ubuntu32:~/riscv-qemu$ ./riscv32-softmmu/qemu-system-riscv32 -nographic -kernel /home/shore/riscv/riscv32-unknown-elf/bin/bbl -drive file=/home/shore/linux-4.6.2/root.bin,format=raw -m 512M
qemu-system-riscv32: cannot set up guest memory 'riscv_spike_board.ram': Cannot allocate memory
```
Actually, the memory of my machine is 4GB. I cannot believe that it is because the memory is not adequate.  I mean that the 32bit OS can access 4GB memory at most, the OS of my computer is 
```
Linux ubuntu32 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:06:37 UTC 2016 i686 i686 i686 GNU/Linux
```
Actually, the bbl is built according to  https://github.com/riscv/riscv-pk/tree/master, except that I modify the configuration because I am running a 32bit Machine
```
../configure --prefix=$RISCV --host=riscv32-unknown-linux-gnu --enable-32bit --with-payload=/home/shore/linux-4.6.2/vmlinux
```
And maybe i should point out the vmlinux is built according to https://github.com/Technolution/riscv-linux/tree/priv-1.9, the drive file system is build according to the https://github.com/riscv/riscv-tools#creating-root-disk

Anyone knows what's wrong with my procedure?

**Comment by sorear** [comment]
spike-board allocates 2GB of memory which it never uses ( https://github.com/riscv/riscv-qemu/blob/master/hw/riscv/riscv_board.c#L142 ) and allocates an additional 2GB to the guest.  Default total memory allocation is 4GB; using the `-m 128M` option will reduce memory usage to 2GB + 128MB; reducing usage below 2GB will probably require code changes.

**Comment by shrshore** [comment]
@sorear Why it should follow the spike-board allocation method? I mean, all the instructions I followed is based on running on qemu, not spike. 
Actually, when build linux kernel, I have written following prompt to remove spike configuration.

```
cp linux-4.6.2/arch/riscv/configs/riscv64_qemu linux-4.6.2/arch/riscv/configs/riscv64_spike
```

**Comment by sagark** [comment]
Try this fix https://github.com/riscv/riscv-qemu/commit/8d870e976709b2d20c9aecc42b6c25594e686bcb

It should get rid of the quick hack that was causing this problem.

**Comment by shrshore** [comment]
Thanks a lot!

**Comment by sagark** [comment]
This fix has been merged
