### ISSUE TITLE
RVC not supported

### ISSUE THREAD

**Issue by brucehoult** [riscv/riscv-qemu#41]
Wow! Surprised me, five years after RVC was proposed. Could not understand why my compiled code didn't run.

Surely can't be hard to do a quick, low performance (pseudocode):

```
if ((ins32 & 0x3) != 0x3){
   ins32 = decode_rvc_to_rv(ins32);
   pc -= 2;
}
```

... and change the PC alignment checking.

**Comment by sorear** [comment]
Good to keep this around for tracking, but otherwise patches welcome (and whoever does those patches will be facing a fairly significant testing burden)

**Comment by bkoppelmann** [comment]
Hi Bruce,

I implemented RVC, see #50.

Cheers,
    Bastian

**Comment by sagark** [comment]
#52 has been merged.

**Comment by brucehoult** [comment]
Thanks so much to @bkoppelmann for doing all the grunt work on this!

I think it's so important for the RISC-V story to be able to tell people it's fully supported in qemu.

And, by the way, my tests show it being two to three times faster than qemu-arm and qemu-aarch64, at about 4x slower than native on Skylake. I assume the lack of condition codes accounts for a lot of that.

RISC-V: easy to implement in hardware, easy to emulate in software.
