### ISSUE TITLE
scripts/qemu-binfmt-conf.sh does not register riscv

### ISSUE THREAD

**Issue by brucehoult** [riscv/riscv-qemu#42]
If the appropriate magic string for riscv elf binaries is added, and pointed to the installed qemu-riscv{32,64} binary, then we can run linux riscv binaries at the command line as if they were x86 binaries.

**Comment by brucehoult** [comment]
Running this as root (not sudo) works for me for RV32 binaries. I didn't study how to integrate it into the script.

    Z='\x00\x00\x00\x00\x00\x00\x00'; echo ':riscv32:M::\x7f\x45\x4c\x46'$Z$Z'\xf3\x00:\xff\xff\xff\xff'$Z$Z'\xff\xff:/usr/local/bin/qemu-riscv32:' >/proc/sys/fs/binfmt_misc/register

**Comment by brucehoult** [comment]
e.g.

    bruce@bruce:~/foo$ cat hello.c
    #include <stdio.h>
    
    int main(int argc, char **argv){
      printf("Hello %s!\n", argc==2 ? argv[1] : "World");
      return 0;
    }
    bruce@bruce:~/foo$ riscv32-unknown-elf-gcc -c -O hello.c -o hello.o
    bruce@bruce:~/foo$ riscv32-unknown-elf-objdump -d hello.o
    
    hello.o:     file format elf32-littleriscv
    
    
    Disassembly of section .text:
    
    00000000 <main>:
       0:	ff010113          	addi	sp,sp,-16
       4:	00112623          	sw	ra,12(sp)
       8:	00200793          	li	a5,2
       c:	02f50663          	beq	a0,a5,38 <.L5>
      10:	000005b7          	lui	a1,0x0
      14:	00058593          	mv	a1,a1
    
    00000018 <.L2>:
      18:	00000537          	lui	a0,0x0
      1c:	00050513          	mv	a0,a0
      20:	00000317          	auipc	t1,0x0
      24:	000300e7          	jalr	t1
      28:	00000513          	li	a0,0
      2c:	00c12083          	lw	ra,12(sp)
      30:	01010113          	addi	sp,sp,16
      34:	00008067          	ret
    
    00000038 <.L5>:
      38:	0045a583          	lw	a1,4(a1) # 4 <main+0x4>
      3c:	fddff06f          	j	18 <.L2>
    bruce@bruce:~/foo$ riscv32-unknown-elf-gcc hello.o -o hello
    bruce@bruce:~/foo$ file hello
    hello: ELF 32-bit LSB executable, UCB RISC-V, version 1 (SYSV), statically linked, not stripped
    bruce@bruce:~/foo$ ./hello Bruce
    Hello Bruce!
    bruce@bruce:~/foo$

**Comment by sorear** [comment]
see also https://github.com/sorear/fedora-riscv-useremu/blob/master/checksetup.c
