### ISSUE TITLE
riscv-linux master branch does not compile with specified riscv-tools -mabi=lp64 not legal option

### ISSUE THREAD

**Issue by jonmcdonald** [riscv/riscv-qemu#53]
The README.md specifies a specific version of riscv-tools, and references the master branch of riscv-linux.  The master branch of riscv-linux was modified on Jan 6, 2017 to use the -mabi switch which is not compatible with the specified version of riscv-tools.  Linux will not build with this configuration.
What version of riscv-linux has been verified?

**Comment by sagark** [comment]
The latest version of linux I've tried is 030e8173dd9379de5c2f065ba73e73
4ff7647ef8

**Comment by michaeljclark** [comment]
I'm closing out this issue as riscv-linux has changed substantially since February. i.e. now supports device-tree and requires an up-to-date riscv-gnu-toolchain. riscv-linux compilation issues should be raised here: https://github.com/riscv/riscv-linux
