### ISSUE TITLE
Update target-riscv/TODO

### ISSUE THREAD

**Issue by farhan90** [riscv/riscv-qemu#65]
Hi,
I am interested with helping port RISC V to QEMU. I am just learning about RISC V architecture and ISA in my attempt to learn more about different computer architecture. 

I have some experience working on QEMU professionally,
https://git.qemu.org/qemu.git/?p=qemu.git&a=search&h=HEAD&st=author&s=Farhan+Ali,
and I would like to help anyway I can to learn more :)

**Comment by poweihuang17** [comment]
@bkoppelmann hi, do you know anything about todo of qemu-riscv? Thank you~ Not sure which one of contributor should we point to.

**Comment by poweihuang17** [comment]
@palmer-dabbelt Palmer, do you know who should we point to? Thanks~

**Comment by palmer-dabbelt** [comment]
@bkoppelmann @sorear @sagark are probably the best bets.  I think QEMU is a very important project and we really need someone to make a concentrated push towards getting it upstream, as it's blocking RISC-V adoption.  Can someone sign up to be the maintainer of QEMU and push it upstream?  If not, then I can, but I'd prefer not to as we're really pushing on Linux+glibc right now.

**Comment by farhan90** [comment]
I am not sure if I can take up the maintainer responsibilities. But I'm willing to help, guide and review patches to help with the upstreaming process for QEMU

**Comment by palmer-dabbelt** [comment]
@farhan90 Ya, that's fine -- the maintainer part was more aimed and the people who can been contributing for a while.

**Comment by sagark** [comment]
@bkoppelmann is taking up maintainer duties/upstreaming, afaik

**Comment by poweihuang17** [comment]
Nice. Maybe the main player could outline the work for 1.9.1 to 1.10 and we could pick up some.

**Comment by bkoppelmann** [comment]
Hi @poweihuang17 and @farhan90,

sorry for the late response. I'm really busy right now with examens since I plan to graduate this semester. I'm working on improving the extensibility of the RISC-V QEMU target (see discussion https://lists.gnu.org/archive/html/qemu-devel/2017-07/msg07735.html) 

I think there are many task that need to be done. I'll update the TODO file in target-riscv in the next days with all the tasks I can think of.

Cheers,
Bastian

**Comment by poweihuang17** [comment]
Nice. Thank you. I'm also a master student trying to graduate at next semester, so I could totally understand your situation. Gogogo!

**Comment by michaeljclark** [comment]
I'm closing this issue because we are using 'Issues' on this GitHub repo for our TODO list.

If you have an Issue, then please raise it...
