### ISSUE TITLE
Minor make clean issue

### ISSUE THREAD

**Issue by mmcco** [riscv/riscv-qemu#8]
This is pretty trivial, but line 269 in the Makefile uses `rm` instead or `rm -f`, so I get prompted to override write protections for five files upon each `make clean`.

**Comment by palmer-dabbelt** [comment]
I looked and the upstream HEAD's Makefile doesn't have a "rm -f" there.  Additionally, this doesn't complain for me.  If you submit an upstream patch to fix the issue then I'll merge it in, that way we won't lose anything when we eventually rebase onto a newer upstream release.
